#!/bin/bash

set -e

exec 3>&1
exec 1>&2

src=$1

source $(dirname $0)/common.sh

if [[ -z "${lock}" ]]; then
	echo "Determining lock name based off of BOSH info: ${bosh_lock}/info"
	lock=$(curl -k ${bosh_lock}/info | jq -r '.name')
	echo "Using ${lock} for lock name"
fi

if [[ -z "$key" ]]; then
	echo >&2 "invalid payload (missing key)"
fi

if [[ "$operation" == "lock" ]]; then
	OP=PUT
elif [[ "$operation" == "unlock" ]]; then
	OP=DELETE
else
	echo >&2 "invalid payload (unrecognized lock_op '$operation' - should be 'lock' or 'unlock)"
	exit 1
fi

payload="{\"key\":\"${key}\"}"
if [[ -n "$locked_by" ]]; then
	payload="{\"key\":\"${key}\",\"requestor\":\"${locked_by}\"}"
fi


set +e
out=$(http_req /lock/${lock} -X $OP -d "${payload}")
rc=$?
set -e

if [[ ${operation} == "lock" ]]; then
	while echo "$out" | grep -q "423 Locked"; do
		echo "$lock" is locked, trying again in 30s
		sleep 30
		set +e
		out=$(http_req /lock/${lock} -X $OP -d "${payload}")
		rc=$?
		set -e
	done
fi

if [[ $rc != 0 ]]; then
	echo >&2 "Failed to communicate with locker:"
	echo >&2 "$out"
	exit 1
fi

echo "$out"

current_ref=$(calc_reference)

echo "$out" | jq "{\"version\": {\"ref\": \"$current_ref\"}, \"metadata\":
  [
   {\"name\":\"lock\",\"value\":\"$lock\"},
   {\"name\":\"status\",\"value\":. | tojson}
  ]}" >&3
