---
# settings for the locker-resource pipeline
meta:
  target: sw
  url:    https://ci.starkandwayne.com
  name:   locker-resource

  initial_version: 0.0.1

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  dockerhub:
    email:    (( vault "secret/dockerhub:email" ))
    username: (( vault "secret/dockerhub:username" ))
    password: (( vault "secret/dockerhub:password" ))
    repository: cfcommunity/locker-resource

  github:
    owner: cloudfoundry-community
    repo:  locker-resource
    private_key:  (( vault "secret/pipelines/locker-resource/github:private" ))
    access_token: (( vault "secret/pipelines/locker-resource/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/locker-resource/slack:webhook" ))
    channel: '#botspam'
